### ISSUE TITLE
Tracking issue for images

### ISSUE THREAD

**Issue by dan-massey** [dan-massey/maf-annual-report#21]
# Title page
- [x] Full bleed background image of two people using mobile app - https://missionassetfund.box.com/s/leh0ju3ik1v8b3q44poo

# Who we are
- [x] Full bleed background image of smiling business owner - https://missionassetfund.app.box.com/s/q9art705qc5i8fbjhi9i

# Reflecting on 2014
- [x] Full size CEO image - https://missionassetfund.app.box.com/s/n1yeh6vl4zx92f7ib29v
- [x] CEO signature image - https://missionassetfund.app.box.com/s/yjdpys7oggjko07qhjlr

# 2014 Highlights
- [x] EXPANDING PARTNERSHIPS - https://missionassetfund.box.com/s/ite6zglrf5k28pnog6ap
- [x] MOVING TO A NEW OFFICE - https://missionassetfund.box.com/s/b8pyps69jy7h2h0i9fur 
- [x] LAUNCHING OUR SOCIAL LOAN PLATFORM - https://missionassetfund.box.com/s/vhx35hb13ughkgzwwe4r
- [x] GETTING A FRESH DESIGN - https://missionassetfund.box.com/s/5ut3kuss9km0at1l7arr
- [x] PROGRAMS - https://missionassetfund.box.com/s/bv569cuorxayqkjyb3lp
- [x] PASSING SB 896 - https://missionassetfund.box.com/s/cckswrv9gi0227ih9idz
- [x] ADDING NEW STAFF - https://missionassetfund.box.com/s/nkhusdnn2304aguppw5j
- [x] EARNING AWARDS - https://missionassetfund.box.com/s/2fiddsf7k9qmcd1ticrw
- [x] MAKING THE MEDIA  - https://missionassetfund.box.com/s/apx4rjt0ph18139nvymk

# Stories
- [x] FROM DREAMS TO MEDICAL SCHOOL (we have a portrait image which I think is final)
- [x] A FAMILY OF CHEFS - https://missionassetfund.box.com/s/b19mos5szf33ufkbd1ja
- [x] SUNSHINE TO THE COMMUNITY - https://missionassetfund.box.com/s/cone9hn34wuyetjf81hv
- [x] Video: A Shot at Success

# Our Impact
- [x] Infographic (1200 x 600)

# Financials
- [x] Growth chart
- [x] Expenses chart

# Looking ahead to 2015
~~Possible missing image (broken image in the doc)~~

# Thank You
- [x] Full bleed group photo - https://missionassetfund.box.com/s/a9sfcjnxc3i7y5niwres
